### ISSUE TITLE
Caching is ineffective when authentication is used

### ISSUE THREAD

**Issue by aaronpk** [alexreisner/geocoder#1048]
It seems that if authentication is used with a provider, then the cache key will include the token, making the cache mostly ineffective, especially if the token changes frequently such as with the Esri provider. 

I see a note in the source that seems to indicate the cache key should not include token information, but can't find any code that does that:

https://github.com/alexreisner/geocoder/blob/6c5769cfb75648ea0b6a9613e77d1463a5a40285/lib/geocoder/lookups/base.rb#L143

Is the intended behavior to use the query string without the token as the cache key? If so, is that something worth fixing in a consistent way across all providers?

**Comment by alexreisner** [comment]
This is true, though I believe ESRI is the only provider where the token changes from one request to the next. This should be solved by implementing the [`cache_key`](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/base.rb#L149) method for the ESRI lookup.

**Comment by aaronpk** [comment]
Sounds good. I have a PR that I can submit in the morning.

**Comment by alexreisner** [comment]
@aaronpk take a look at f8ce952 and let me know if you have any objections to this solution.

**Comment by aaronpk** [comment]
@alexreisner that looks like it will work fine for the Esri provider. I do still have a concern for the other providers too though. It strikes me as a potential security issue that this gem is caching these tokens on the other providers though. For some providers, using the tokens actually charges people money, so the tokens need to be protected. Stashing them off in caches where they are potentially being logged or visible by other parts of a system is not a good idea, and certainly not a decision that I would want a gem to make for me. I will open a new issue for this specifically.

**Comment by alexreisner** [comment]
Totally agree. Thanks!
